#
# >>> DON'T CHANGE THIS FILE. <<<
# 
# Copy this file as Makefile.mine and set the variables in that copy. The 
# Makefile.mine will be included by the root Makefile, but ignored by git.
#

#
# Program to build.
#
# -------- Project path and name default values ------------------------
# Project path
# relative to this folder, leave void if the project is in this folder
PROJECT_PATH = apps
# Project name
PROJECT_NAME = ej2
